services:
  - type: static
    name: front-junta-vecinos
    runtime: static
    branch: prodution  # Asegúrate que este es el nombre correcto de tu rama
    rootDir: sistema-junta-vecinal/front-junta-vecinos  # Directorio donde está el package.json
    buildCommand: npm install && npm run build
    staticPublishPath: build  # Relativo al rootDir
    envVars:
      - key: NODE_VERSION
        value: 18.17.0  # Específica una versión de Node más estable
      - key: REACT_APP_API_URL
        value: https://mysite-ix48.onrender.com
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - sistema-junta-vecinal/front-junta-vecinos/**/*
      ignoredPaths:
        - sistema-junta-vecinal/front-junta-vecinos/node_modules/**/*